### ISSUE TITLE
新版本登录接口返回值加密

### ISSUE THREAD

**Issue by mirai-MIC** [github123666/gonxueyun#10]
```

POST
/session/user/v5/login
## 请求头

##返回值

b06
{"code":200,"msg":"success","data":"23bd07ced818b**************************************************************f28b7"}
0

```

请问下作者大大，您知道这个解密怎么算吗

**Comment by mirai-MIC** [comment]
这个是小黄鸟抓到的

**Comment by github123666** [comment]
> 这个是小黄鸟抓到的

加密变了吗？新版本之前看了加密在native层不好逆向(主要是菜)

**Comment by mirai-MIC** [comment]
> > 这个是小黄鸟抓到的
> 
> 加密变了吗？新版本之前看了加密在native层不好逆向(主要是菜)

请求加密我看了下之前的，都没有变
只有登录返回数据有加密

**Comment by github123666** [comment]
> > > 这个是小黄鸟抓到的
> > 
> > 
> > 加密变了吗？新版本之前看了加密在native层不好逆向(主要是菜)
> 
> 请求加密我看了下之前的，都没有变 只有登录返回数据有加密
用加密的密钥解,对称加密。

**Comment by mirai-MIC** [comment]
> > > > 这个是小黄鸟抓到的
> > > 
> > > 
> > > 加密变了吗？新版本之前看了加密在native层不好逆向(主要是菜)
> > 
> > 请求加密我看了下之前的，都没有变 只有登录返回数据有加密
> 用加密的密钥解,对称加密。

好的打扰您了，谢谢，祝您有愉快的一天
